import Globalstate from "@/context";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>{/* Add your head content here */}</head>
      <body className={inter.className}>
        <Globalstate>
          <Navbar />
          <main>{children}</main>
        </Globalstate>
      </body>
    </html>
  );
}
